import { List, ListItem, Stack, ThemeIcon, Title, rem } from '@mantine/core';
import { IconCircleCheck, IconCircleDashed } from '@tabler/icons-react';
import React from 'react';

const Home: React.FC = () => {
  return (
    <Stack w="100%" p="sm">
      <Title>Home</Title>
      <Stack>
        <Title order={2}>This area will contain quick bits of information about the store</Title>
        <p>Recent orders, easy to understand stats, insights, recommendations, etc.</p>
        <p>
          In general it will be kept very simple. Like the Shopify Admin Home but with a lot less
          going on.
        </p>
        <Title order={2}>Admin Demo Stage 1</Title>
        <p style={{ fontWeight: 500, fontSize: 18 }}>Key goals:</p>
        <List
          spacing="xs"
          withPadding
          icon={
            <ThemeIcon color="teal" size={24}>
              <IconCircleCheck style={{ width: rem(16), height: rem(16) }} />
            </ThemeIcon>
          }
        >
          <ListItem>
            Create an Auth (login/logout) system that links a user account to their generated Store.
          </ListItem>
          <ListItem>
            Create a system that connects the Shopify account with the logged in user. It fetches
            user-specific data providing a customized view of their store's info.
          </ListItem>
          <ListItem>
            Create a dashboard based on Shopify with less confusion, large icons, fewer options.
            "All necessities with no fluff".
          </ListItem>
          <ListItem>
            Pull Orders From Main Shopify Store that were generated by this specific "sub-store".
          </ListItem>
          <ListItem>
            Simulate generated products and display their basic info: total inventory, prices,
            variants, etc.
          </ListItem>
          <ListItem>
            Display customers that were created by this store. For example when an order is created
            by this store and an email address is captured, a new customer is created that is
            associated with this store.
          </ListItem>
          <ListItem
            icon={
              <ThemeIcon color="blue" size={24}>
                <IconCircleDashed style={{ width: rem(16), height: rem(16) }} />
              </ThemeIcon>
            }
          >
            Add advanced section with more advanced stats, modification options, and marketing tools.
          </ListItem>
          <ListItem
            icon={
              <ThemeIcon color="blue" size={24} style={{ visibility: 'hidden' }}>
                <IconCircleDashed style={{ width: rem(16), height: rem(16) }} />
              </ThemeIcon>
            }
          >
            <List withPadding>
              <ListItem>
                Mostly in the planning/testing phase. I've been working on how to create custom
                database queries to Shopify to generate reports with success (more info in Advanced{' '}
                {'>'} Stats). In planning phase for creating more in-depth store theme
                customizations. In planning phase for creating simplified marketing tools.
              </ListItem>
            </List>
          </ListItem>
        </List>
      </Stack>
    </Stack>
  );
};

export default Home;
